# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME

# begin_font_config
font_family FantasqueSansM Nerd Font Mono 
bold_font FantasqueSansM Nerd Font Mono Bold
italic_font FantasqueSansM Nerd Font Mono Italic
bold_italic_font FantasqueSansM Nerd Font Mono Bold Italic
#font_family SauceCodePro Nerd Font Mono ExtraLight
#bold_font SauceCodePro Nerd Font Light
#italic_font SauceCodePro Nerd Font ExtraLight Italic
#bold_italic_font SauceCodePro Nerd Font Light Italic
#font_family VictorMono Nerd Font Mono ExtraLight Italic
#bold_font VictorMono Nerd Font Mono Bold Italic
#italic_font VictorMono Nerd Font Mono Medium Italic
#bold_italic_font VictorMono Nerd Font Mono Bold Italic
#font_family Fantasque Sans Mono
#bold_font Fantasque Sans Mono Bold
#italic_font Fantasque Sans Mono Italic
#bold_italic_font Fantasque Sans Mono Italic Bold
#font_family AnonymicePro Nerd Font
#bold_font AnonymicePro Nerd Font Bold
#italic_font AnonymicePro Nerd Font Italic
#bold_italic_font AnonymicePro Nerd Font Italic Bold
#font_family VictorMono Nerd Font Mono 
#bold_font VictorMono Nerd Font Mono Bold
#italic_font VictorMono Nerd Font Mono Italic
#bold_italic_font VictorMono Nerd Font Mono Italic Bold
font_size 14.0
# end_font_config

# begin_tab_bar_config
tab_title_template "{index}: {title[title.rfind('/')+1:]}"
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_min_tabs 1
# end_tab_bar_config

# start_tab_n_window_config
map kitty_mod+t new_tab_with_cwd
map kitty_mod+enter new_window_with_cwd
map kitty_mod+n new_os_window_with_cwd
map super+t new_tab_with_cwd
map super+enter new_window_with_cwd
map super+n new_os_window_with_cwd
# end_tab_n_window_config

# begin_macos_specific
macos_option_as_alt true
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66
map super+left send_text all \x01
map super+right send_text all \x05
map super+backspace send_text all \x15
map kitty_mod+k clear_terminal clear_scrollback
map super+k clear_terminal clear_scrollback
# map kitty_mod+k clear_terminal clear only_active
# map super+k clear_terminal clear only_active
# end_macos_specific

# begin_pager_settings
scrollback_pager nvim - "+setl ft=terminal concealcursor=nc"
# end_pager_settings
