source ~/.vimrcplug
source ~/.vimrcmain
source ~/.vimrc_settings_basic
source ~/.vimrc_functions

" ####### Plugin: config: syntastic
let g:syntastic_swift_checkers = ['swiftpm', 'swiftlint']

"Testing
" source ~/.vim/svimft.vim

" SourceKit-LSP configuration
if executable('sourcekit-lsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'sourcekit-lsp',
        \ 'cmd': {server_info->['sourcekit-lsp']},
        \ 'whitelist': ['swift'],
        \ })
endif

autocmd FileType swift setlocal omnifunc=lsp#complete
autocmd FileType swift nnoremap <C-]> :LspDefinition<CR>


"--------------------------------------
" Overriding vim functions
"--------------------------------------

""" Netrw overrides, these are the instruction to make Netrw come up by default for every vim command
"nmap <Leader>n :Vexplore .<CR>
"augroup ProjectDrawer
"  autocmd!
"  autocmd VimEnter * :Vexplore . | wincmd p
"augroup END

""" This are the config and remapping of Netrw
"let g:netrw_banner = 0
"let g:netrw_liststyle = 3
"let g:netrw_browse_split = 4
"let g:netrw_altv = 1
"let g:netrw_winsize = 12
"
"autocmd filetype netrw call Netrw_mappings()
"function! Netrw_mappings()
"  noremap <buffer>% :call CreateInPreview()<cr>
"endfunction
"
"function! CreateInPreview()
"  let l:filename = input("please enter filename: ")
"  execute 'silent !touch ' . b:netrw_curdir.'/'.l:filename
"  redraw!
"endf

"--------------------------------------
" END: Overriding vim functions
"--------------------------------------
"
