
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Local secrets (credentials, tokens — not tracked in git)
[[ -f "$HOME/.config/boot/secrets.env" ]] && source "$HOME/.config/boot/secrets.env"

# Android SDK
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$GOPATH/bin

# Paths
export PATH=$PATH:/usr/local/bin/flutter/bin
export PATH=$PATH:~/.boot/scripts
export PATH=$PATH:/usr/local/kafka/bin

# for Apple Silicon M1
export PATH=/opt/homebrew/bin:$PATH
export PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/Cellar/openssl@1.1/1.1.1n/lib/pkgconfig

# .bashrc, .zshrc or whatever shell you use
export PATH=$PATH:$HOME/.local/bin:$HOME/Library/Python/3.9/bin

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/usr/local/go/bin:$PATH

############################################################################################################### END PATH VARIABLE SETUP

export TERM=xterm-256color
# aliases
alias spm="swift package"
alias xcode="open -a /Applications/Xcode.app"
alias tx=tmuxinator
alias vpncon='open "https://sign.devops.krungthai.com/" && osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "connect \"CLIENT\"" -e "end tell"'
alias vpndis='osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "disconnect \"CLIENT\"" -e "end tell"'
alias tomcatstart='/opt/homebrew/Cellar/tomcat/10.1.10/libexec/bin/startup.sh'
alias tomcatstop='/opt/homebrew/Cellar/tomcat/10.1.10/libexec/bin/shutdown.sh'
alias tomcatrun='/opt/homebrew/Cellar/tomcat/10.1.10/libexec/bin/catalina.sh run'

# function-as-alias `idea`
idea() {
    open -na $HOME/Applications/JetBrains\ Toolbox/IntelliJ\ IDEA\ Ultimate.app --args "$@"
}

studio() {
    open -na "Android Studio.app" --args "$@"
}

alias vim='nvim'
alias vimdiff='nvimdiff'
export JDTLS_JVM_ARGS="-javaagent:/usr/local/share/lombok/lombok.jar"

# docker local development setup (comes from SMART ELCID project)
export ENV_FILE=.env.docker-local

# eval $(minikube -p minikube docker-env)
#export DOCKER_TLS_VERIFY="1"
#export DOCKER_HOST="tcp://192.168.49.2:2376"
#export DOCKER_CERT_PATH="$HOME/.minikube/certs"
#export MINIKUBE_ACTIVE_DOCKERD="minikube"
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://127.0.0.1:44459"
export DOCKER_CERT_PATH="$HOME/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

#eval $(minikube docker-env)

export LC_ALL=en_US.UTF-8
export GOPATH=$HOME
export GO111MODULE=on
export GOPRIVATE=gitdev.devops.krungthai.com/*,gitdev.inno.ktb/*
export GOPROXY=https://artifact.devops.krungthai.com/repository/goproxy,direct
export GONOSUMDB=gitdev.inno.ktb/*,gitdev.devops.krungthai.com/*

# Google Cloud
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# Variables
export JRE_HOME=~/.sdkman/candidates/java/current

# Path to your oh-my-zsh installation.
DISABLE_AUTO_UPDATE=true
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_THEME="materialshell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# change tab title to current dir
# Uncomment the following line to disable auto-setting terminal title.
# TODO: This causes about 0.025s
#DISABLE_AUTO_TITLE="true"
#function precmd () {
#    #print -Pn "\e]0;%~\a"
#    window_title="\033]0;${PWD##*/}\007"
#    echo -ne "$window_title"
#}
#function chpwd () {
#    window_title="\033]0;${PWD##*/}\007"
#    echo -ne "$window_title"
#}


# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions)

# TODO: This attributes about 0.17s of load time, but it's hard to get rid of things inside it
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# TODO: This causes a lot of startup time (about 0.15s)
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="$HOME/.sdkman"
#[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/Downloads/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/Downloads/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc"; fi

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="$HOME/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
alias luamake="$HOME/Downloads/luamake/luamake"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

## TODO: This causes a alot of startup time (about 0.4s)
#eval "$(rbenv init - zsh)"
